# -*- coding: utf-8 -*-
"""src/agent.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qk7QM2xN6vPrA0ACI3MxqR8081d5TfFu
"""

# src/agent.py
class Agent:
    def __init__(self, env, start, goal):
        self.env = env
        self.start = start
        self.goal = goal
        self.path = []
        self.path_cost = None

    def set_path(self, path, cost):
        self.path = path
        self.path_cost = cost